- name: Deploy Flask app and configure systemd service
  hosts: app
  become: yes
  tasks:
    - name: Git clone Flask app repository
      git:
        repo: https://github.com/saaverdo/flask-alb-app
        dest: /home/ubuntu/flask-alb-app
        version: orm

    - name: Install Python requirements
      pip:
        requirements: /home/ubuntu/flask-alb-app/requirements.txt
        extra_args: "--no-cache-dir"

    - name: Include vars file
      include_vars:
        file: vars.yml

    - name: Create systemd service file from template
      template:
        src: app.service.j2
        dest: /etc/systemd/system/app.service

    - name: Reload systemd manager configuration
      systemd:
        daemon_reload: yes

    - name: Start app service
      systemd:
        name: app
        state: started
        enabled: yes
